#!/bin/bash
set -euo pipefail

# Script to generate 02-area-generated.sql with embedded shapefile data
# Converts ZIP files from database/init/shapefiles/ to hex-encoded bytea values

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHAPEFILE_DIR="${SCRIPT_DIR}/shapefiles"
OUTPUT_FILE="${SCRIPT_DIR}/02-area-generated.sql"

# Check if shapefiles directory exists
if [ ! -d "${SHAPEFILE_DIR}" ]; then
    echo "ERROR: Shapefiles directory not found: ${SHAPEFILE_DIR}" >&2
    exit 1
fi

# Function to convert a file to hex-encoded SQL bytea
# Args: $1 = file path
# Returns: PostgreSQL decode() statement for the hex data
encode_file_to_hex() {
    local file_path="$1"

    if [ ! -f "${file_path}" ]; then
        echo "ERROR: File not found: ${file_path}" >&2
        exit 1
    fi

    # Convert file to hex using xxd
    # -p: plain hexdump (no line numbers, no ASCII)
    # -c 0: output continuous hex string (no line breaks)
    local hex_data
    hex_data=$(xxd -p -c 0 "${file_path}")

    # Return PostgreSQL decode function
    echo "decode('${hex_data}', 'hex')::bytea"
}

# Define area
# Format: "competent_authority_area_id|filename|zipfile|competent_authority_id|comment"
declare -a AREAS=(
    "amsterdam-area0363|Amsterdam.zip|Amsterdam.zip|c4ac8ccf-a281-5789-bad7-28dfac20ca7f|Amsterdam area"
    "rotterdam-area0599|Rotterdam.zip|Rotterdam.zip|a30df3a7-7e38-534c-b9c0-7666bad077d2|Rotterdam area"
    "denhaag-area0518|Den-Haag.zip|Den-Haag-dummy.zip|363ce948-b057-54f3-a916-5dd127a93986|Den Haag area"
    "amstelveen-area0362|Amstelveen.zip|Amstelveen-dummy.zip|05cd4276-7fb6-58f9-ba53-b4b8bb841800|Amstelveen area"
    "bergen-area0373|Bergen.zip|Bergen-dummy.zip|4c2cae62-415c-5e4f-8365-64867c97acd1|Bergen (Noord-Holland) area"
    "delft-area0503|Delft.zip|Delft.zip|a296eb87-dcef-5edc-a173-f749bde80f11|Delft area"
    "diemen-area0384|Diemen.zip|Diemen.zip|67fed8cf-b536-507e-8489-af4e1cb04ba5|Diemen area"
    "gouda-area0513|Gouda.zip|Gouda.zip|843c21a2-10d0-51a7-81c7-510a7d265b6e|Gouda area"
    "groningen-area0014|Groningen.zip|Groningen.zip|8c1f41c4-0d6f-516a-b626-89cea0370f15|Groningen area"
    "haarlem-area0392|Haarlem.zip|Haarlem.zip|3d648d22-19f5-5c6f-bef3-d2ac6ad6d514|Haarlem area"
    "katwijk-area0537|Katwijk.zip|Katwijk.zip|51658261-9835-5e57-8089-ff7b14097e5a|Katwijk area"
    "landsmeer-area0415|Landsmeer.zip|Landsmeer.zip|2c43298f-c4f2-5dbf-b8dc-9506e4606fda|Landsmeer area"
    "leiden-area0546|Leiden.zip|Leiden.zip|6499b306-44a4-5379-9a16-190acaa0475b|Leiden area"
    "maastricht-area0935|Maastricht.zip|Maastricht.zip|6df9eba2-b88d-502e-8ae4-92ded9684460|Maastricht area"
    "middelburg-area0687|Middelburg.zip|Middelburg.zip|3f9f0b48-a7de-5a8f-bb39-192970cc3478|Middelburg area"
    "noordwijk-area0575|Noordwijk.zip|Noordwijk.zip|ace23ca2-f935-53c4-a239-d6cb06d3c042|Noordwijk area"
    "pijnackernootdorp-area1926|Pijnacker-Nootdorp-dummy.zip|Pijnacker-Nootdorp-dummy.zip|303daae2-4e70-553f-bc7d-c9af7b5c89ac|Pijnacker-Nootdorp area"
    "renkum-area0274|Renkum.zip|Renkum.zip|d7e79bbe-4dff-5ffe-8d9a-d22930d12545|Renkum area"
    "sluis-area1714|Sluis.zip|Sluis.zip|20a03a70-7bab-5cc0-b1f4-396f2f11760c|Sluis area"
    "schouwenduiveland-area1676|Schouwen-Duiveland.zip|Schouwen-Duiveland.zip|08dea277-4956-52df-95d7-8113d1a6e8cc|Schouwen-Duiveland area"
    "texel-area0448|Texel.zip|Texel.zip|703b2f59-8aca-5812-b96d-09a6be47e183|Texel area"
    "utrecht-area0344|Utrecht.zip|Utrecht.zip|7a4039df-9ca4-55f7-9b21-2aa28f4c9da6|Utrecht area"
    "vlissingen-area0718|Vlissingen.zip|Vlissingen.zip|acd71d83-5105-5a0e-8dbc-20d5bf761f69|Vlissingen area"
    "voorschoten-area0626|Voorschoten-dummy.zip|Voorschoten-dummy.zip|5fc653b6-ada0-527b-86f1-21a01bebd650|Voorschoten area"
    "waterland-area0852|Waterland.zip|Waterland.zip|e416d9f1-be38-560e-8f50-89af3b935e8f|Waterland area"
    "zaanstad-area0479|Zaanstad.zip|Zaanstad.zip|2e665ac8-b3e2-511a-995d-5dfb7a349554|Zaanstad area"
    "zandvoort-area0473|Zandvoort.zip|Zandvoort.zip|524dde6b-e353-525e-ac6e-fa56d58222e1|Zandvoort area"
    "zwolle-area0193|Zwolle.zip|Zwolle.zip|10f2b986-802c-537f-82d2-8069a25c6c11|Zwolle area"
)

# Start writing the SQL file
cat > "${OUTPUT_FILE}" <<'EOF'
-- Insert areas with embedded shapefile data
--
-- WARNING: This file is auto-generated by postgres-prep-area-sql.sh
-- DO NOT EDIT THIS FILE MANUALLY!
--
-- To regenerate this file with updated shapefile data, run:
--   ./test-data/postgres-prep-area-sql.sh
--
-- The shapefile ZIP files are hex-encoded and embedded directly in this SQL file.
-- This approach works in all environments without requiring volume mounts or superuser privileges.

EOF

# Generate SQL for each area
for area_def in "${AREAS[@]}"; do
    IFS='|' read -r competent_authority_area_id filename zipfile ca_id comment <<< "${area_def}"

    zipfile_path="${SHAPEFILE_DIR}/${zipfile}"

    echo "Processing ${comment} (${zipfile})..."

    # Check if the ZIP file exists
    if [ ! -f "${zipfile_path}" ]; then
        echo "ERROR: Shapefile not found: ${zipfile_path}" >&2
        echo "ERROR: Cannot generate SQL without all shapefiles." >&2
        exit 1
    fi

    # Get hex-encoded data
    hex_bytea=$(encode_file_to_hex "${zipfile_path}")

    # Generate a stable RFC 9562 UUID for the area_id (functional ID).
    # Keep this deterministic so Swagger examples can point at seeded rows.
    area_uuid=$(python3 -c "import uuid; print(str(uuid.uuid5(uuid.NAMESPACE_URL, 'sdep-area:${competent_authority_area_id}')))")

    # Extract area name from comment (e.g., "Amsterdam area" -> "Amsterdam")
    area_name=$(echo "${comment}" | sed 's/ area$//')

    # Write SQL INSERT statement
    cat >> "${OUTPUT_FILE}" <<EOF
-- ${comment}
INSERT INTO area (competent_authority_id, area_id, area_name, regulation, filename, filedata, created_at)
VALUES (
  (SELECT id FROM competent_authority WHERE competent_authority_id = '${ca_id}'),
  '${area_uuid}',
  '${area_name}',
  'all',
  '${filename}',
  ${hex_bytea},
  '2025-01-01 00:00:00+00'::timestamptz
) ON CONFLICT (area_id, competent_authority_id, created_at) DO NOTHING;

EOF
done

echo ""
echo "✓ Successfully generated ${OUTPUT_FILE}"
echo "✓ Processed ${#AREAS[@]} areas with embedded shapefile data"
echo ""
echo "The SQL file now contains hex-encoded shapefile data and is ready for database initialization."
