"""CRUD operations for Activity model."""

from datetime import datetime

from sqlalchemy import func, insert, select, update
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.enums import ActivityStatus
from app.models.activity import Activity
from app.models.area import Area
from app.models.competent_authority import CompetentAuthority
from app.schemas.activity import ActivityBulkCreate


async def create(
    session: AsyncSession,
    activity_id: str | None,
    activity_name: str | None,
    platform_id: int,
    area_id: int,
    url: str,
    address_thoroughfare: str,
    address_locator_designator_number: int | None,
    address_locator_designator_letter: str | None,
    address_locator_designator_addition: str | None,
    address_post_code: str,
    address_post_name: str,
    address_full_address: str,
    registration_number: str,
    number_of_guests: int,
    country_of_guests: list[str],
    temporal_start_date_time: datetime,
    temporal_end_date_time: datetime,
    status: ActivityStatus = ActivityStatus.finished,
) -> Activity:
    """
    Create a new activity.

    Args:
        session: Async database session
        activity_id: Functional ID. If not provided, auto-generated by model.
        activity_name: Display name (optional, max 64 characters).
        platform_id: Platform id (foreign key to Platform, required)
        area_id: Area id (foreign key to Area, required, integer)
        url: URL (128 characters, required)
        address_thoroughfare: Street / public space name (required, max 80 chars)
        address_locator_designator_number: Numeric house number (optional, >= 0 when provided)
        address_locator_designator_letter: Letter/character suffix (optional, max 10 chars)
        address_locator_designator_addition: Additional qualifier (optional, max 128 chars)
        address_post_code: Postal code (required, max 10 chars)
        address_post_name: City / town / village (required, max 80 chars)
        address_full_address: Full address as a single string (required, max 318 chars)
        registration_number: Registration number (required, max 32 chars)
        number_of_guests: Number of guests (1-1024)
        country_of_guests: Array of country codes (required, each ISO 3166-1 alpha-3 or 'N/A';
            length must equal number_of_guests — enforced by caller)
        temporal_start_date_time: Temporal start datetime (required)
        temporal_end_date_time: Temporal end datetime (required)
        status: Lifecycle status ('finished' by default, or 'cancelled').

    Returns:
        Created Activity instance
    """
    activity = Activity(
        activity_id=activity_id,
        activity_name=activity_name,
        status=status,
        platform_id=platform_id,
        area_id=area_id,
        url=url,
        address_thoroughfare=address_thoroughfare,
        address_locator_designator_number=address_locator_designator_number,
        address_locator_designator_letter=address_locator_designator_letter,
        address_locator_designator_addition=address_locator_designator_addition,
        address_post_code=address_post_code,
        address_post_name=address_post_name,
        address_full_address=address_full_address,
        registration_number=registration_number,
        number_of_guests=number_of_guests,
        country_of_guests=country_of_guests,
        temporal_start_date_time=temporal_start_date_time,
        temporal_end_date_time=temporal_end_date_time,
    )
    session.add(activity)
    await session.flush()
    await session.refresh(activity)
    return activity


async def exists(session: AsyncSession, activity_id: int) -> bool:
    """
    Check if an activity exists by technical id.

    Args:
        session: Async database session
        activity_id: Activity technical id (integer)

    Returns:
        True if exists, False otherwise
    """
    stmt = select(Activity.id).where(Activity.id == activity_id)
    result = await session.execute(stmt)
    return result.scalar_one_or_none() is not None


async def count(session: AsyncSession) -> int:
    """
    Count all activities.

    Args:
        session: Async database session

    Returns:
        Total number of activities
    """
    stmt = select(func.count()).select_from(Activity)
    result = await session.execute(stmt)
    return result.scalar_one()


async def get_all(
    session: AsyncSession, offset: int = 0, limit: int | None = None
) -> list[Activity]:
    """
    Get all activities with pagination.

    Args:
        session: Async database session
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of Activity instances
    """
    stmt = select(Activity).offset(offset)
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_by_id(session: AsyncSession, activity_id: int) -> Activity | None:
    """
    Get an activity by technical id (internal use only).

    Args:
        session: Async database session
        activity_id: Activity technical id (integer)

    Returns:
        Activity instance or None if not found
    """
    stmt = select(Activity).where(Activity.id == activity_id)
    result = await session.execute(stmt)
    return result.scalar_one_or_none()


async def get_by_activity_id(
    session: AsyncSession, activity_id: str
) -> Activity | None:
    """
    Get current activity by functional ID (ended_at IS NULL).

    Args:
        session: Async database session
        activity_id: Activity functional ID

    Returns:
        Current Activity instance for the given activity_id, or None if not found
    """
    stmt = select(Activity).where(
        Activity.activity_id == activity_id,
        Activity.ended_at.is_(None),
    )
    result = await session.execute(stmt)
    return result.scalar_one_or_none()


async def get_by_url(
    session: AsyncSession, url: str, offset: int = 0, limit: int | None = None
) -> list[Activity]:
    """
    Get activities by url with pagination.

    Args:
        session: Async database session
        url: URL
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of Activity instances matching the url
    """
    stmt = select(Activity).where(Activity.url == url).offset(offset)
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_by_registration_number(
    session: AsyncSession,
    registration_number: str,
    offset: int = 0,
    limit: int | None = None,
) -> list[Activity]:
    """
    Get activities by registration number with pagination.

    Args:
        session: Async database session
        registration_number: Registration number
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of Activity instances matching the registration number
    """
    stmt = (
        select(Activity)
        .where(Activity.registration_number == registration_number)
        .offset(offset)
    )
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_by_platform_id(
    session: AsyncSession, platform_id: int, offset: int = 0, limit: int | None = None
) -> list[Activity]:
    """
    Get activities by platform_id (foreign key) with pagination.

    Args:
        session: Async database session
        platform_id: Platform id (foreign key to Platform)
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of Activity instances matching the platform_id
    """
    stmt = select(Activity).where(Activity.platform_id == platform_id).offset(offset)
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_by_area_id(
    session: AsyncSession, area_id: int, offset: int = 0, limit: int | None = None
) -> list[Activity]:
    """
    Get activities by area_id (foreign key - technical ID) with pagination.

    Args:
        session: Async database session
        area_id: Area technical id (foreign key to Area, integer)
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of Activity instances for the given area_id
    """
    stmt = select(Activity).where(Activity.area_id == area_id).offset(offset)
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_by_competent_authority_client_id(
    session: AsyncSession,
    client_id: str,
    offset: int = 0,
    limit: int | None = None,
) -> list[Activity]:
    """
    Get current activities by competent authority private client_id.

    Args:
        session: Async database session
        client_id: Private authentication client identifier
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of current Activity instances for the authenticated competent authority
    """
    stmt = (
        select(Activity)
        .options(
            selectinload(Activity.platform),
            selectinload(Activity.area).selectinload(Area.competent_authority),
        )
        .join(Area, Activity.area_id == Area.id)
        .join(CompetentAuthority, Area.competent_authority_id == CompetentAuthority.id)
        .where(
            CompetentAuthority.client_id == client_id,
            Activity.ended_at.is_(None),
        )
        .order_by(Activity.created_at.desc(), Activity.id.desc())
        .offset(offset)
    )
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def count_by_competent_authority_client_id(
    session: AsyncSession,
    client_id: str,
) -> int:
    """
    Count current activities by competent authority private client_id.

    Args:
        session: Async database session
        client_id: Private authentication client identifier

    Returns:
        Total number of current activities for the authenticated competent authority
    """
    stmt = (
        select(func.count())
        .select_from(Activity)
        .join(Area, Activity.area_id == Area.id)
        .join(CompetentAuthority, Area.competent_authority_id == CompetentAuthority.id)
        .where(
            CompetentAuthority.client_id == client_id,
            Activity.ended_at.is_(None),
        )
    )
    result = await session.execute(stmt)
    return result.scalar_one()


async def exists_any_by_activity_id(
    session: AsyncSession,
    activity_id: str,
) -> bool:
    """
    Check if any version of an activity exists by functional ID (regardless of ended_at).

    Args:
        session: Async database session
        activity_id: Activity functional ID

    Returns:
        True if any version exists, False otherwise
    """
    stmt = (
        select(func.count())
        .select_from(Activity)
        .where(Activity.activity_id == activity_id)
    )
    result = await session.execute(stmt)
    return result.scalar_one() > 0


async def mark_as_ended(
    session: AsyncSession,
    activity_id: str,
    platform_id: int,
) -> None:
    """
    Mark the current version of an activity as ended (set ended_at = now()).

    Args:
        session: Async database session
        activity_id: Activity functional ID
        platform_id: Platform technical ID (foreign key)
    """
    stmt = (
        update(Activity)
        .where(
            Activity.activity_id == activity_id,
            Activity.platform_id == platform_id,
            Activity.ended_at.is_(None),
        )
        .values(ended_at=func.now())
    )
    await session.execute(stmt)
    await session.flush()


async def bulk_mark_as_ended(
    session: AsyncSession,
    activity_ids: list[str],
    platform_id: int,
) -> None:
    """
    Batch mark current versions of activities as ended (set ended_at = now()).

    Used for activity versioning in bulk operations: a single UPDATE marks all
    existing current versions as ended before the bulk INSERT creates new versions.

    Args:
        session: Async database session
        activity_ids: List of activity functional IDs to mark as ended
        platform_id: Platform technical ID (foreign key)
    """
    if not activity_ids:
        return

    stmt = (
        update(Activity)
        .where(
            Activity.activity_id.in_(activity_ids),
            Activity.platform_id == platform_id,
            Activity.ended_at.is_(None),
        )
        .values(ended_at=func.now())
    )
    await session.execute(stmt)
    await session.flush()


async def bulk_create(
    session: AsyncSession,
    activities: list[ActivityBulkCreate],
) -> None:
    """
    Bulk insert activities using a single multi-row INSERT (Validation flow Step 3).

    Only pre-validated records should be passed to this function.
    All application-level validation (Pydantic, RI check, deactivation guard)
    must be completed before calling this.

    Args:
        session: Async database session
        activities: List of validated activity objects with resolved technical IDs
    """
    if not activities:
        return

    activity_rows = [
        {
            "activity_id": activity.activity_id,
            "activity_name": activity.activity_name,
            "status": activity.status,
            "platform_id": activity.platform_technical_id,
            "area_id": activity.area_technical_id,
            "url": activity.url,
            "address_thoroughfare": activity.address.thoroughfare,
            "address_locator_designator_number": activity.address.locator_designator_number,
            "address_locator_designator_letter": activity.address.locator_designator_letter,
            "address_locator_designator_addition": activity.address.locator_designator_addition,
            "address_post_code": activity.address.post_code,
            "address_post_name": activity.address.post_name,
            "address_full_address": activity.address.full_address,
            "registration_number": activity.registration_number,
            "number_of_guests": activity.number_of_guests,
            "country_of_guests": activity.country_of_guests,
            "temporal_start_date_time": activity.temporal.start_date_time,
            "temporal_end_date_time": activity.temporal.end_date_time,
            "created_at": activity.created_at,
        }
        for activity in activities
    ]

    stmt = insert(Activity)
    await session.execute(stmt, activity_rows)
    await session.flush()


async def get_current_by_activity_ids(
    session: AsyncSession,
    activity_ids: list[str],
    platform_id: int,
    *,
    for_update: bool = False,
) -> dict[str, bool]:
    """
    Check which activity IDs have current versions (ended_at IS NULL) for a platform.

    Returns a dict mapping activity_id to True if a current version exists.
    Used for bulk activity versioning to determine which IDs need mark-as-ended.

    Args:
        session: Async database session
        activity_ids: List of activity functional IDs
        platform_id: Platform technical ID
        for_update: If True, acquire row-level locks (SELECT ... FOR UPDATE)

    Returns:
        Dictionary {activity_id: True} for IDs that have a current version
    """
    if not activity_ids:
        return {}

    stmt = select(Activity.activity_id).where(
        Activity.activity_id.in_(activity_ids),
        Activity.platform_id == platform_id,
        Activity.ended_at.is_(None),
    )
    if for_update:
        stmt = stmt.with_for_update()
    result = await session.execute(stmt)
    return {row[0]: True for row in result.all()}


async def get_deactivated_activity_ids(
    session: AsyncSession,
    activity_ids: list[str],
) -> set[str]:
    """
    Find activity IDs that are deactivated (exist but have NO current version).

    An activity is deactivated if it has at least one version but all versions
    have ended_at set. Creating a new version for a deactivated entity is rejected.

    Args:
        session: Async database session
        activity_ids: List of activity functional IDs to check

    Returns:
        Set of activity_ids that are deactivated
    """
    if not activity_ids:
        return set()

    # Find IDs that exist in the database at all
    stmt_any = (
        select(Activity.activity_id)
        .where(Activity.activity_id.in_(activity_ids))
        .distinct()
    )
    result_any = await session.execute(stmt_any)
    all_existing = {row[0] for row in result_any.all()}

    # Find IDs that have a current version (ended_at IS NULL)
    stmt_current = (
        select(Activity.activity_id)
        .where(
            Activity.activity_id.in_(activity_ids),
            Activity.ended_at.is_(None),
        )
        .distinct()
    )
    result_current = await session.execute(stmt_current)
    has_current = {row[0] for row in result_current.all()}

    # Deactivated = exists but no current version
    return all_existing - has_current
