"""CRUD operations for CompetentAuthority model."""

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.competent_authority import CompetentAuthority


async def create(
    session: AsyncSession,
    client_id: str,
    competent_authority_id: str | None = None,
    competent_authority_name: str | None = None,
) -> CompetentAuthority:
    """
    Create a new competent authority.

    Args:
        session: Async database session
        client_id: Private authentication client identifier.
        competent_authority_id: Public competent authority functional identifier.
            Generated by the model when omitted.
        competent_authority_name: Competent authority display name (max 64 characters, e.g. "Amsterdam")

    Returns:
        Created CompetentAuthority instance
    """
    competent_authority = CompetentAuthority(
        client_id=client_id,
        competent_authority_name=competent_authority_name,
    )
    if competent_authority_id is not None:
        competent_authority.competent_authority_id = competent_authority_id
    session.add(competent_authority)
    await session.flush()
    await session.refresh(competent_authority)
    return competent_authority


async def exists(session: AsyncSession, id: int) -> bool:
    """
    Check if a competent authority exists by id.

    Args:
        session: Async database session
        id: CompetentAuthority id

    Returns:
        True if exists, False otherwise
    """
    stmt = select(CompetentAuthority.id).where(CompetentAuthority.id == id)
    result = await session.execute(stmt)
    return result.scalar_one_or_none() is not None


async def count(session: AsyncSession) -> int:
    """
    Count all competent authorities.

    Args:
        session: Async database session

    Returns:
        Total number of competent authorities
    """
    stmt = select(func.count()).select_from(CompetentAuthority)
    result = await session.execute(stmt)
    return result.scalar_one()


async def get_all(
    session: AsyncSession, offset: int = 0, limit: int | None = None
) -> list[CompetentAuthority]:
    """
    Get current competent authorities with pagination (ended_at IS NULL).

    Args:
        session: Async database session
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of current CompetentAuthority instances
    """
    stmt = (
        select(CompetentAuthority)
        .where(CompetentAuthority.ended_at.is_(None))
        # Secondary sort on id ensures deterministic pagination order when rows share the same created_at
        .order_by(CompetentAuthority.created_at.desc(), CompetentAuthority.id.desc())
        .offset(offset)
    )
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_by_id(session: AsyncSession, id: int) -> CompetentAuthority | None:
    """
    Get a competent authority by id.

    Args:
        session: Async database session
        id: CompetentAuthority id

    Returns:
        CompetentAuthority instance or None if not found
    """
    stmt = select(CompetentAuthority).where(CompetentAuthority.id == id)
    result = await session.execute(stmt)
    return result.scalar_one_or_none()


async def get_by_client_id(
    session: AsyncSession,
    client_id: str,
    *,
    for_update: bool = False,
) -> CompetentAuthority | None:
    """
    Get current competent authority by private client_id (ended_at IS NULL).

    Args:
        session: Async database session
        client_id: Private authentication client identifier
        for_update: If True, acquire a row-level lock (SELECT ... FOR UPDATE)

    Returns:
        Current CompetentAuthority instance for the given client_id, or None if not found
    """
    stmt = select(CompetentAuthority).where(
        CompetentAuthority.client_id == client_id,
        CompetentAuthority.ended_at.is_(None),
    )
    if for_update:
        stmt = stmt.with_for_update()
    result = await session.execute(stmt)
    return result.scalar_one_or_none()


async def get_by_competent_authority_name(
    session: AsyncSession,
    competent_authority_name: str,
    offset: int = 0,
    limit: int | None = None,
) -> list[CompetentAuthority]:
    """
    Get current competent authorities by competent_authority_name with pagination (ended_at IS NULL).

    Args:
        session: Async database session
        competent_authority_name: Competent authority name
        offset: Number of records to skip (default: 0)
        limit: Maximum number of records to return (default: no limit)

    Returns:
        List of current CompetentAuthority instances matching the competent_authority_name
    """
    stmt = (
        select(CompetentAuthority)
        .where(
            CompetentAuthority.competent_authority_name == competent_authority_name,
            CompetentAuthority.ended_at.is_(None),
        )
        # Secondary sort on id ensures deterministic pagination order when rows share the same created_at
        .order_by(CompetentAuthority.created_at.desc(), CompetentAuthority.id.desc())
        .offset(offset)
    )
    if limit is not None:
        stmt = stmt.limit(limit)

    result = await session.execute(stmt)
    return list(result.scalars().all())


async def exists_any_by_client_id(
    session: AsyncSession,
    client_id: str,
) -> bool:
    """
    Check if any version of a competent authority exists by private client_id.

    Args:
        session: Async database session
        client_id: Private authentication client identifier

    Returns:
        True if any version exists, False otherwise
    """
    stmt = (
        select(func.count())
        .select_from(CompetentAuthority)
        .where(CompetentAuthority.client_id == client_id)
    )
    result = await session.execute(stmt)
    return result.scalar_one() > 0


async def mark_as_ended_by_client_id(
    session: AsyncSession,
    client_id: str,
) -> None:
    """
    Mark the current version of a competent authority as ended by private client_id.

    Args:
        session: Async database session
        client_id: Private authentication client identifier
    """
    stmt = (
        update(CompetentAuthority)
        .where(
            CompetentAuthority.client_id == client_id,
            CompetentAuthority.ended_at.is_(None),
        )
        .values(ended_at=func.now())
    )
    await session.execute(stmt)
    await session.flush()
